import shutil
from pathlib import Path
from datetime import datetime
from jinja2 import Environment, FileSystemLoader
from rich.console import Console
from .config import AzSOARConfig

console = Console()

class PlaybookGenerator:
    def __init__(self, config: AzSOARConfig):
        self.config = config
        self.template_dir = Path(__file__).parent / "templates"
        self.env = Environment(
            loader=FileSystemLoader(self.template_dir),
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def generate(self, template_name: str, output_dir: Path, custom_name: str = None) -> Path:
        """Generate playbook from template"""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        template_path = self.template_dir / template_name
        if not template_path.exists():
            raise ValueError(
                f"Template '{template_name}' not found.\n"
                f"Available: phishing-response, identity-compromise, ransomware-containment"
            )

        playbook_name = custom_name or f"azsoar-{template_name.replace('_', '-')}"
        target_dir = output_dir / playbook_name
        target_dir.mkdir(exist_ok=True)

        context = {
            "playbook_name": playbook_name,
            "tenant_id": self.config.tenant_id,
            "subscription_id": self.config.subscription_id,
            "workspace_id": self.config.workspace_id,
            "resource_group": self.config.resource_group,
            "author": "AzSOAR Framework",
        }

        # Render templates and copy files
        for item in template_path.rglob("*"):
            relative_path = item.relative_to(template_path)
            target_path = target_dir / relative_path

            if item.is_dir():
                target_path.mkdir(exist_ok=True)
            else:
                if item.suffix in (".bicep", ".json", ".md", ".yaml"):
                    template = self.env.get_template(str(item.relative_to(self.template_dir)))
                    rendered = template.render(**context)
                    target_path.write_text(rendered)
                else:
                    shutil.copy2(item, target_path)

        # Create README
        (target_dir / "README.md").write_text(self._generate_readme(template_name, playbook_name))
        
        console.print(f"[green]✅ Playbook generated:[/] {target_dir}")
        return target_dir

    def _generate_readme(self, template_name: str, playbook_name: str) -> str:
        """Generate clean README"""
        return f"""# {playbook_name}

**Auto-generated by AzSOAR** on {datetime.now().strftime('%Y-%m-%d %H:%M')}

**Template**: {template_name}

## Deployment

```bash
az deployment group create \\
  --resource-group YOUR_RG \\
  --template-file main.bicep \\
  --parameters workspaceId={self.config.workspace_id or 'YOUR-WORKSPACE-ID'}
  Description
This playbook was generated for {template_name.replace('_', ' ').title()} scenarios using the AzSOAR framework.
Next Steps

Review and customize workflow.json
Deploy using the command above
Test locally with azsoar test


Generated with ❤️ by AzSOAR
"""
